trigger:
  - main

variables:
  - group: k8s

pool: k8s

jobs:
  - job: build
    steps:
      - script: |
          set -euxo pipefail
          docker build -f Dockerfile -t "fnwicr.azurecr.io/testapp:latest" .
          docker push "fnwicr.azurecr.io/testapp:latest"
        displayName: Build Docker container
        workingDirectory: ./TestApp.Web
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))

      - script: |
          set -euxo pipefail
          VERSION="0.${BUILD_BUILDNUMBER}"
          helm package --version "${VERSION}" --app-version "${VERSION}" charts/testapp
          helm push "testapp-${VERSION}.tgz" oci://fnwicr.azurecr.io/helm
          curl "https://k8s.datanose.nl/gitops-updater?name=testapp&secret=${UPDATER_SECRET}&version=${VERSION}"
        displayName: Build Helm chart and push to registry
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
        env:
          UPDATER_SECRET: $(DEPLOY_SECRET)